nonzero_exit_errors = true
path = ["/opt/google-cloud-sdk/bin", "/usr/local/bin", "/usr/local/sbin", "/usr/bin", "/var/lib/flatpak/exports/bin", "/usr/lib/jvm/default/bin", "/usr/bin/site_perl", "/usr/bin/vendor_perl", "/usr/bin/core_perl", "/home/kevin/.bin", "/home/kevin/.local/bin", "/home/kevin/.yarn/bin", "/home/kevin/.config/yarn/global/node_modules/.bin", "/home/kevin/.pub-cache/bin", "/home/kevin/Android/flutter/bin", "/home/kevin/Android/sdk/platform-tools", "/home/kevin/.cargo/bin", "/home/kevin/.antigen/bundles/robbyrussell/oh-my-zsh/lib", "/home/kevin/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git", "/home/kevin/.antigen/bundles/zsh-users/zsh-autosuggestions", "/home/kevin/.antigen/bundles/zsh-users/zsh-completions", "/home/kevin/.antigen/bundles/zsh-users/zsh-syntax-highlighting"]
prompt = "echo $(starship prompt)"
skip_welcome_message = true
startup = ["alias l [] { ls | sort-by type }", "alias lt [] { ls | sort-by type | select name type size }"]
table_mode = "light"

[env]
ANDROID_SDK_ROOT = "/home/kevin/Android/sdk"
CLOUDSDK_PYTHON = "python"
CLOUDSDK_PYTHON_ARGS = "-S"
CLOUDSDK_ROOT_DIR = "/opt/google-cloud-sdk"
COLORTERM = "truecolor"
DBUS_SESSION_BUS_ADDRESS = "unix:path=/run/user/1000/bus"
DESKTOP_SESSION = "gnome-xorg"
DISPLAY = ":1"
EDITOR = "nvim"
GDMSESSION = "gnome-xorg"
GDM_LANG = "en_US.UTF-8"
GIO_LAUNCHED_DESKTOP_FILE_PID = "14742"
GOOGLE_CLOUD_SDK_HOME = "/opt/google-cloud-sdk"
HG = "/usr/bin/hg"
HOME = "/home/kevin"
INVOCATION_ID = "8d10a7b4742a4508b33ec4580e3101f4"
JAVA_HOME = "/usr/lib/jvm/java-8-openjdk"
JOURNAL_STREAM = "8:39028"
KITTY_WINDOW_ID = "1"
LANG = "en_US.UTF-8"
LC_MEASUREMENT = "en_US.UTF-8"
LC_MONETARY = "en_US.UTF-8"
LC_NUMERIC = "en_US.UTF-8"
LC_PAPER = "en_US.UTF-8"
LC_TIME = "en_US.UTF-8"
LESS = "-R"
LOGNAME = "kevin"
LSCOLORS = "Gxfxcxdxbxegedabagacad"
LS_COLORS = "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36::tw=35;04:ow=34;04"
MAIL = "/var/spool/mail/kevin"
MAKEFLAGS = "-j5 -l4"
MANAGERPID = "1699"
NB_CORES = "4"
OLDPWD = "/home/kevin"
PAGER = "less"
PWD = "/home/kevin"
QT_STYLE_OVERRIDE = "kvantum"
RUSTC_WRAPPER = "sccache"
SESSION_MANAGER = "local/bebop:@/tmp/.ICE-unix/1846,unix/bebop:/tmp/.ICE-unix/1846"
SHELL = "/usr/bin/zsh"
SHLVL = "1"
SSH_AUTH_SOCK = "/run/user/1000/keyring/ssh"
STARSHIP_SHELL = ""
SUDO_PROMPT = "Password 🔐: "
TERM = "xterm-kitty"
TERMINFO = "/usr/lib/kitty/terminfo"
USER = "kevin"
USERNAME = "kevin"
VISUAL = "nvim"
WINDOWID = "39845902"
WINDOWPATH = "2"
XAUTHORITY = "/run/user/1000/gdm/Xauthority"
XDG_CURRENT_DESKTOP = "GNOME"
XDG_DATA_DIRS = "/home/kevin/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/"
XDG_MENU_PREFIX = "gnome-"
XDG_RUNTIME_DIR = "/run/user/1000"
XDG_SESSION_CLASS = "user"
XDG_SESSION_DESKTOP = "gnome-xorg"
XDG_SESSION_TYPE = "x11"
_ = "/usr/bin/nu"
_JAVA_OPTIONS = "-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true"
