#!/bin/bash


masked=$(systemctl status sleep.target suspend.target hibernate.target hybrid-sleep.target | grep "masked")

if [[ -z $masked ]]; then 
    sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
else
    sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target
fi
