#!/bin/bash

GTK_THEME=$1
GRES_XML="gnome-shell-theme.gresource.xml"

echo "Generating gnome-shell-theme.gresource.xml for theme ${GTK_THEME}"

if [[ -d "$HOME/.themes/${GTK_THEME}/gnome-shell" ]]; then 
    NEEDS_SUDO=false
    cd "$HOME/.themes/${GTK_THEME}/gnome-shell"
else 
    NEEDS_SUDO=true
    cd "/usr/share/themes/${GTK_THEME}/gnome-shell"
fi

clear_xml() {
    if $NEEDS_SUDO; then
        echo -n "" | sudo tee "${GRES_XML}"
    else
        echo -n "" | tee "${GRES_XML}"
    fi
}

write_xml() {
    LINE="$1"
    if $NEEDS_SUDO; then
        echo "${LINE}" | sudo tee -a "${GRES_XML}"
    else
        echo "${LINE}" | tee -a "${GRES_XML}"
    fi
}

clear_xml

write_xml "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" 
write_xml "<gresources>" 
write_xml "  <gresource prefix=\"/org/gnome/shell/theme\">"

shopt -s globstar
for file in **/*; do
    [[ -d "$file" ]] && continue
    [[ "$file" = "gnome-shell-theme.gresource.xml" ]] && continue
    [[ "$file" =~ ".*\.md$" ]] && continue

    write_xml "    <file>${file}</file>"
done 

write_xml "  </gresource>"
write_xml "</gresources>"
