linux:
  splash-image: /usr/share/systemd/bootctl/splash-arch.bmp

  flavors:
    default:
      cmdline: cmdline
      output: /boot/EFI/Linux/archlinux.efi

    fallback:
      enabled: false
      title: "Arch Linux (fallback)"
      cmdline: cmdline
      output: /boot/EFI/Linux/archlinux-fallback.efi

